import { existsSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'

/** A setting in a `{% schema %}`, as far as its type needs. */
interface Setting {
  type?: string
  id?: string
  options?: { value?: unknown }[]
}

interface Schema {
  settings?: Setting[]
  blocks?: { type?: string; settings?: Setting[] }[]
}

/** The types of the theme's section and block settings, and the files whose schema couldn't be read. */
export interface SettingsTypes {
  source: string
  warnings: string[]
}

const textTypes = new Set([
  'text',
  'textarea',
  'html',
  'richtext',
  'inline_richtext',
  'liquid',
  'url',
])

// prettier breaks a longer line, so a long union is written the way prettier writes it
const printWidth = 100

/**
 * Generates TypeScript types for the settings in the `{% schema %}` of the theme's
 * `sections/*.liquid` and `blocks/*.liquid`: `SectionSettings`, `BlockSettings` and `SectionBlockSettings`.
 */
export function settingsTypes(themeDir: string): SettingsTypes {
  const warnings: string[] = []
  const sections = readSchemas(path.join(themeDir, 'sections'), warnings)
  const blocks = readSchemas(path.join(themeDir, 'blocks'), warnings)

  const sectionBlocks: string[][] = []
  for (const [name, schema] of sections) {
    // @theme and @app refer to blocks defined elsewhere
    const local = (schema.blocks ?? []).filter(
      (block): block is { type: string; settings?: Setting[] } =>
        typeof block.type === 'string' && !block.type.startsWith('@'),
    )
    if (!local.length) continue
    sectionBlocks.push([
      `  ${key(name)}: {`,
      ...local.flatMap((block) => settingsProperty(block.type, block.settings ?? [], '    ')),
      '  }',
    ])
  }

  const lines = [
    '// Generated by @pelagojs/vite-plugin from the {% schema %} of sections/ and blocks/. Do not edit.',
    '/* eslint-disable */',
    '',
    '/** The settings of each section, by file name. */',
    ...interfaceLines(
      'SectionSettings',
      sections.map(([name, schema]) => settingsProperty(name, schema.settings ?? [], '  ')),
    ),
    '',
    '/** The settings of each theme block in `blocks/`, by file name. */',
    ...interfaceLines(
      'BlockSettings',
      blocks.map(([name, schema]) => settingsProperty(name, schema.settings ?? [], '  ')),
    ),
    '',
    '/** The settings of the blocks defined in a section, by section file name, then block type. */',
    ...interfaceLines('SectionBlockSettings', sectionBlocks),
    '',
  ]
  return { source: lines.join('\n'), warnings }
}

/** An exported interface with the given properties, each already written as lines. */
function interfaceLines(name: string, properties: string[][]): string[] {
  if (!properties.length) return [`export interface ${name} {}`]
  return [`export interface ${name} {`, ...properties.flat(), '}']
}

/** One property holding a type literal of settings, e.g. `'hello-world': { heading: string | null }`. */
function settingsProperty(name: string, settings: Setting[], indent: string): string[] {
  const valued = settings.filter((setting) => typeof setting.id === 'string' && setting.type)
  if (!valued.length) return [`${indent}${key(name)}: {}`]
  const lines = [`${indent}${key(name)}: {`]
  for (const setting of valued) {
    const prefix = `${indent}  ${key(setting.id!)}: `
    const types = settingType(setting)
    const line = prefix + types.join(' | ')
    if (types.length > 1 && line.length > printWidth) {
      lines.push(prefix.trimEnd(), ...types.map((type) => `${indent}    | ${type}`))
    } else {
      lines.push(line)
    }
  }
  lines.push(`${indent}}`)
  return lines
}

/** The type of a setting's value, as a list of union members. */
export function settingType(setting: Setting): string[] {
  switch (setting.type) {
    case 'checkbox':
      return ['boolean']
    case 'range':
      return ['number']
    case 'number':
      return ['number', 'null']
    case 'select':
    case 'radio': {
      const values = (setting.options ?? [])
        .map((option) => option.value)
        .filter((value) => typeof value === 'string')
      return values.length ? [...new Set(values)].map(literal) : ['string']
    }
    case 'text_alignment':
      return ["'left'", "'center'", "'right'"]
    default:
      // resources, colors and fonts: the island gets whatever shape its Liquid builds
      return textTypes.has(setting.type!) ? ['string', 'null'] : ['unknown']
  }
}

/** The schemas of the `.liquid` files in a folder, by file name, sorted. */
function readSchemas(dir: string, warnings: string[]): [string, Schema][] {
  if (!existsSync(dir)) return []
  const schemas: [string, Schema][] = []
  for (const file of readdirSync(dir).sort()) {
    if (path.extname(file) !== '.liquid') continue
    const schema = parseSchema(readFileSync(path.join(dir, file), 'utf8'))
    if (schema instanceof Error) {
      warnings.push(`${path.basename(dir)}/${file}: ${schema.message}`)
      continue
    }
    if (schema) schemas.push([path.basename(file, '.liquid'), schema])
  }
  return schemas
}

/** The JSON in a file's `{% schema %}` tag: `null` without one, an `Error` if it isn't a JSON object. */
export function parseSchema(liquid: string): Schema | null | Error {
  const match = /{%-?\s*schema\s*-?%}([\s\S]*?){%-?\s*endschema\s*-?%}/.exec(liquid)
  if (!match) return null
  try {
    const schema: unknown = JSON.parse(match[1]!)
    if (typeof schema !== 'object' || schema === null || Array.isArray(schema))
      return new Error('the schema is not a JSON object')
    return schema as Schema
  } catch (error) {
    return new Error(`the schema is not valid JSON (${(error as Error).message})`)
  }
}

function key(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : literal(name)
}

/** A string literal, quoted the way prettier quotes it with `singleQuote`. */
function literal(value: string): string {
  if (value.includes("'") && !value.includes('"')) return JSON.stringify(value)
  const escaped = JSON.stringify(value).slice(1, -1).replace(/\\"/g, '"').replace(/'/g, "\\'")
  return `'${escaped}'`
}
