import { existsSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'

/** The file name of the translations snippet, in the theme's `snippets/` folder. */
export const translationsSnippetFile = 'pelago-translations.liquid'

/** A string of the default locale: its plural forms, if it has them, and its `{{ placeholders }}`. */
interface LocaleString {
  forms: string[] | null
  vars: string[]
}

/** The translations snippet and types, and what the scan couldn't use. */
export interface Translations {
  snippet: string
  types: string
  warnings: string[]
}

export interface TranslationsInput {
  /** The theme's folder, with `locales/`. */
  themeDir: string
  /** The folder of the island code to scan for `t('…')` calls. */
  scanDir: string
  /** Keys to render even when the scan doesn't find them, such as keys built at runtime. */
  include?: string[]
}

const pluralForms = ['zero', 'one', 'two', 'few', 'many', 'other']
const sourceExtensions = new Set(['.vue', '.ts', '.tsx', '.mts', '.js', '.jsx', '.mjs', '.svelte'])
const keyPattern = /^[\w-]+(\.[\w-]+)*$/

// prettier breaks a longer line, so a long type is written the way prettier writes it
const printWidth = 100

/**
 * Generates the translations snippet, which renders the strings the islands use through Liquid's `t` filter,
 * and the types of the theme's translation keys, from `locales/*.default.json`.
 */
export function translations({ themeDir, scanDir, include = [] }: TranslationsInput): Translations {
  const warnings: string[] = []
  const strings = readDefaultLocale(themeDir, warnings)
  const otherForms = readPluralForms(themeDir)

  const used = new Set(include)
  for (const [file, source] of readSources(scanDir)) {
    const { keys, dynamic } = findKeys(source)
    for (const key of keys) used.add(key)
    const relative = path.relative(themeDir, file)
    for (const line of dynamic)
      warnings.push(
        `${relative}:${line}: t() with a key the scan can't read; add it to translations.include`,
      )
  }

  const lines: string[] = []
  for (const key of [...used].sort()) {
    const string = strings?.get(key)
    if (!keyPattern.test(key) || (strings && !string)) {
      warnings.push(`t('${key}'): no such key in locales/*.default.json`)
      continue
    }
    // every plural form any locale has, as the request's language may need one the default lacks
    const forms = string?.forms
      ? [...new Set([...string.forms, ...(otherForms.get(key) ?? [])])]
      : null
    for (const name of forms ? forms.map((form) => `${key}.${form}`) : [key])
      lines.push(`"${name}":{{ '${name}' | t | json }}`)
  }

  const snippet = [
    '{% comment %}',
    '  Generated by @pelagojs/vite-plugin from the t() calls of the islands. Do not edit.',
    "  The strings the islands use, in the request's locale, for the global data island.",
    '{% endcomment -%}',
    `{${lines.join(',\n')}}`,
    '',
  ].join('\n')
  return { snippet, types: typesSource(strings), warnings }
}

/** The types of the keys, each with its variables, for `t()` in `@pelagojs/shopify`. */
function typesSource(strings: Map<string, LocaleString> | null): string {
  const properties = [...(strings ?? [])].map(([key, { forms, vars }]) => {
    const names = [...new Set([...(forms ? ['count'] : []), ...vars])]
    const fields = names.map(
      (name) => `${quote(name)}: ${name === 'count' && forms ? 'number' : 'string | number'}`,
    )
    const line = `    ${quote(key)}: { ${fields.join('; ')} }`
    if (!fields.length) return `    ${quote(key)}: {}`
    if (line.length <= printWidth) return line
    return [`    ${quote(key)}: {`, ...fields.map((field) => `      ${field}`), '    }'].join('\n')
  })
  return [
    '// Generated by @pelagojs/vite-plugin from locales/*.default.json. Do not edit.',
    '/* eslint-disable */',
    'export {}',
    '',
    "declare module '@pelagojs/shopify' {",
    "  /** The keys of the theme's locale files, each with its variables. */",
    properties.length ? '  interface TranslationKeys {' : '  interface TranslationKeys {}',
    ...(properties.length ? [...properties, '  }'] : []),
    '}',
    '',
  ].join('\n')
}

function quote(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`
}

/** The strings of `locales/*.default.json`, by key, or `null` if the theme has none. */
function readDefaultLocale(themeDir: string, warnings: string[]): Map<string, LocaleString> | null {
  const dir = path.join(themeDir, 'locales')
  const file = existsSync(dir)
    ? readdirSync(dir).find((name) => name.endsWith('.default.json'))
    : undefined
  if (!file) return null
  let json: unknown
  try {
    json = JSON.parse(readFileSync(path.join(dir, file), 'utf8'))
  } catch (error) {
    warnings.push(`locales/${file}: ${(error as Error).message}`)
    return null
  }
  const strings = new Map<string, LocaleString>()
  for (const [key, value] of flatten(json)) {
    if (typeof value === 'string') strings.set(key, { forms: null, vars: placeholders(value) })
    else
      strings.set(key, {
        forms: Object.keys(value),
        vars: [...new Set(Object.values(value).flatMap(placeholders))],
      })
  }
  return strings
}

/** The plural forms of each plural key, in all the theme's storefront locales. */
function readPluralForms(themeDir: string): Map<string, string[]> {
  const dir = path.join(themeDir, 'locales')
  const forms = new Map<string, string[]>()
  if (!existsSync(dir)) return forms
  for (const file of readdirSync(dir)) {
    if (!file.endsWith('.json') || file.endsWith('.schema.json')) continue
    let json: unknown
    try {
      json = JSON.parse(readFileSync(path.join(dir, file), 'utf8'))
    } catch {
      continue
    }
    for (const [key, value] of flatten(json))
      if (typeof value !== 'string')
        forms.set(key, [...(forms.get(key) ?? []), ...Object.keys(value)])
  }
  return forms
}

/** The strings of a locale file by key, with an object of plural forms (`one`, `other`, ...) as one string. */
function flatten(json: unknown, prefix = ''): [string, string | Record<string, string>][] {
  if (!json || typeof json !== 'object') return []
  const entries: [string, string | Record<string, string>][] = []
  for (const [name, value] of Object.entries(json)) {
    const key = prefix + name
    if (typeof value === 'string') entries.push([key, value])
    else if (isPlural(value)) entries.push([key, value as Record<string, string>])
    else entries.push(...flatten(value, key + '.'))
  }
  return entries
}

function isPlural(value: unknown): boolean {
  if (!value || typeof value !== 'object') return false
  const entries = Object.entries(value)
  return (
    'other' in value &&
    entries.every(([form, string]) => pluralForms.includes(form) && typeof string === 'string')
  )
}

function placeholders(string: string): string[] {
  return [...string.matchAll(/\{\{\s*([\w-]+)\s*\}\}/g)].map((match) => match[1]!)
}

/** The source files under a folder, skipping `node_modules`, type declarations and tests. */
function readSources(dir: string): [string, string][] {
  if (!existsSync(dir)) return []
  const files: [string, string][] = []
  for (const entry of readdirSync(dir, { withFileTypes: true, recursive: true })) {
    if (!entry.isFile() || !sourceExtensions.has(path.extname(entry.name))) continue
    if (/\.d\.[mc]?ts$|\.(test|spec)\.\w+$/.test(entry.name)) continue
    const file = path.join(entry.parentPath, entry.name)
    if (file.split(path.sep).includes('node_modules')) continue
    files.push([file, readFileSync(file, 'utf8')])
  }
  return files.sort(([a], [b]) => a.localeCompare(b))
}

/**
 * The keys of the `t('…')` calls in a file that imports `t` from a `@pelagojs/` package,
 * and the lines of calls whose key isn't a plain string.
 */
export function findKeys(source: string): { keys: string[]; dynamic: number[] } {
  if (
    !/import\s*\{[^}]*(?<![\w$]\s*as\s*)\bt\b(?!\s*as\b)[^}]*\}\s*from\s*['"]@pelagojs\//.test(
      source,
    )
  )
    return { keys: [], dynamic: [] }
  const keys: string[] = []
  const dynamic: number[] = []
  for (const match of source.matchAll(
    /(?<![\w$.])t\(\s*(?:'([^'\n]*)'|"([^"\n]*)"|`([^`$]*)`)?/g,
  )) {
    const key = match[1] ?? match[2] ?? match[3]
    if (key !== undefined) keys.push(key)
    else dynamic.push(source.slice(0, match.index).split('\n').length)
  }
  return { keys, dynamic }
}
