// @vitest-environment node
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { format } from 'prettier'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { findKeys, translations } from './translations.js'

let theme: string

function write(file: string, content: string) {
  mkdirSync(path.dirname(path.join(theme, file)), { recursive: true })
  writeFileSync(path.join(theme, file), content)
}

const locale = {
  '404': { title: '404' },
  cart: {
    title: 'Cart',
    item_count: { one: '{{ count }} item', other: '{{ count }} items' },
    shipping_html: 'Free shipping over {{ amount }} to {{country}}',
  },
  gift_card: { expires_on: 'Expires on {{ expires_on }}' },
}

beforeEach(() => {
  theme = mkdtempSync(path.join(tmpdir(), 'translations-'))
  write('locales/en.default.json', JSON.stringify(locale))
  write('locales/en.default.schema.json', JSON.stringify({ names: { header: 'Header' } }))
})

afterEach(() => rmSync(theme, { recursive: true, force: true }))

function run(include?: string[]) {
  return translations({ themeDir: theme, scanDir: path.join(theme, 'src'), include })
}

describe('findKeys', () => {
  it('finds the keys of t() calls in files that import t from Pelago', () => {
    const source = [
      "import { formatMoney, t } from '@pelagojs/shopify'",
      "const a = t('cart.title')",
      'const b = t("cart.item_count", { count })',
      'const c = t(`gift_card.expires_on`)',
      "const d = cart.t('not.this') + format('nor.this')",
    ].join('\n')
    expect(findKeys(source)).toEqual({
      keys: ['cart.title', 'cart.item_count', 'gift_card.expires_on'],
      dynamic: [],
    })
  })

  it('finds calls in a Vue template', () => {
    const source = [
      '<script setup lang="ts">',
      "import { t } from '@pelagojs/shopify'",
      '</script>',
      '<template>',
      `  <button :aria-label="t('cart.title')">{{ t('cart.item_count', { count: 2 }) }}</button>`,
      '</template>',
    ].join('\n')
    expect(findKeys(source).keys).toEqual(['cart.title', 'cart.item_count'])
  })

  it('reports the lines of keys it cannot read', () => {
    const source = [
      "import { t } from '@pelagojs/shopify'",
      't(key)',
      't(`cart.${name}`)',
      "t('cart.title')",
    ].join('\n')
    expect(findKeys(source)).toEqual({ keys: ['cart.title'], dynamic: [2, 3] })
  })

  it("skips files whose t is not Pelago's", () => {
    expect(findKeys("import { t } from 'i18next'\nt('cart.title')").keys).toEqual([])
    expect(findKeys("import { t as translate } from '@pelagojs/shopify'\nt('a.b')").keys).toEqual(
      [],
    )
    expect(findKeys("const t = (s) => s\nt('cart.title')").keys).toEqual([])
  })
})

describe('translations', () => {
  it('renders the keys the islands use, with every plural form', () => {
    write(
      'src/islands/Cart.vue',
      "import { t } from '@pelagojs/shopify'\nt('cart.title')\nt('cart.item_count', { count })",
    )
    write('src/parts/Price.ts', "import { t } from '@pelagojs/shopify'\nt('cart.title')")
    write(
      'src/islands/Cart.test.ts',
      "import { t } from '@pelagojs/shopify'\nt('gift_card.expires_on')",
    )
    write(
      'src/node_modules/x/index.js',
      "import { t } from '@pelagojs/shopify'\nt('gift_card.expires_on')",
    )
    write(
      'locales/pl.json',
      JSON.stringify({ cart: { item_count: { one: '', few: '', many: '', other: '' } } }),
    )
    const { snippet, warnings } = run(['404.title'])
    expect(warnings).toEqual([])
    expect(snippet).toBe(
      [
        '{% comment %}',
        '  Generated by @pelagojs/vite-plugin from the t() calls of the islands. Do not edit.',
        "  The strings the islands use, in the request's locale, for the global data island.",
        '{% endcomment -%}',
        `{"404.title":{{ '404.title' | t | json }},`,
        `"cart.item_count.one":{{ 'cart.item_count.one' | t | json }},`,
        `"cart.item_count.other":{{ 'cart.item_count.other' | t | json }},`,
        `"cart.item_count.few":{{ 'cart.item_count.few' | t | json }},`,
        `"cart.item_count.many":{{ 'cart.item_count.many' | t | json }},`,
        `"cart.title":{{ 'cart.title' | t | json }}}`,
        '',
      ].join('\n'),
    )
  })

  it('renders an empty object when the islands use no keys', () => {
    expect(run().snippet).toMatch(/\n\{\}\n$/)
  })

  it('warns about unknown keys and keys it cannot read', () => {
    write('src/islands/Cart.vue', "import { t } from '@pelagojs/shopify'\nt('cart.titel')\nt(key)")
    const { snippet, warnings } = run(["it's.bad"])
    expect(snippet).not.toContain('titel')
    expect(warnings).toEqual([
      "src/islands/Cart.vue:3: t() with a key the scan can't read; add it to translations.include",
      "t('cart.titel'): no such key in locales/*.default.json",
      "t('it's.bad'): no such key in locales/*.default.json",
    ])
  })

  it('types each key with its variables, as prettier writes it', async () => {
    const { types } = run()
    expect(types).toContain(
      [
        "declare module '@pelagojs/shopify' {",
        "  /** The keys of the theme's locale files, each with its variables. */",
        '  interface TranslationKeys {',
        "    '404.title': {}",
        "    'cart.title': {}",
        "    'cart.item_count': { count: number }",
        "    'cart.shipping_html': { amount: string | number; country: string | number }",
        "    'gift_card.expires_on': { expires_on: string | number }",
        '  }',
        '}',
      ].join('\n'),
    )
    expect(
      await format(types, {
        parser: 'typescript',
        semi: false,
        singleQuote: true,
        printWidth: 100,
      }),
    ).toBe(types)
  })

  it('types no keys for a theme without locales', async () => {
    rmSync(path.join(theme, 'locales'), { recursive: true })
    const { types, snippet } = run()
    expect(types).toContain('  interface TranslationKeys {}\n')
    expect(snippet).toMatch(/\n\{\}\n$/)
    expect(
      await format(types, {
        parser: 'typescript',
        semi: false,
        singleQuote: true,
        printWidth: 100,
      }),
    ).toBe(types)
  })
})
