// Generated by @pelagojs/vite-plugin from the {% schema %} of sections/ and blocks/. Do not edit.
/* eslint-disable */

/** The settings of each section, by file name. */
export interface SectionSettings {
  '404': {}
  'announcement-countdown': {
    message: string | null
    ends_at: string | null
    ended_message: string | null
    show_seconds: boolean
  }
  article: {}
  blog: {}
  cart: {}
  collection: {}
  collections: {
    grid_item_width: 'collections--compact' | 'collections--full'
    grid_gap: number
  }
  'custom-section': {
    background_image: unknown
  }
  footer: {
    menu: unknown
    show_payment_icons: boolean
  }
  header: {
    menu: unknown
    customer_account_menu: unknown
  }
  'hello-world': {
    greeting: string | null
  }
  page: {}
  password: {}
  product: {}
  search: {}
}

/** The settings of each theme block in `blocks/`, by file name. */
export interface BlockSettings {
  group: {
    layout_direction: 'group--horizontal' | 'group--vertical'
    alignment: 'flex-start' | 'center' | 'flex-end'
    padding: number
  }
  text: {
    text: string | null
    text_style: 'text--title' | 'text--subtitle' | 'text--normal'
    alignment: 'left' | 'center' | 'right'
  }
}

/** The settings of the blocks defined in a section, by section file name, then block type. */
export interface SectionBlockSettings {}
