// Generated by @pelagojs/vite-plugin from locales/*.default.json. Do not edit.
/* eslint-disable */
export {}

declare module '@pelagojs/shopify' {
  /** The keys of the theme's locale files, each with its variables. */
  interface TranslationKeys {
    '404.title': {}
    '404.not_found': {}
    '404.back_to_shopping': {}
    'blog.article_comments': {}
    'blog.article_metadata_html': { date: string | number; author: string | number }
    'blog.comment_form_body': {}
    'blog.comment_form_email': {}
    'blog.comment_form_name': {}
    'blog.comment_form_submit': {}
    'blog.comment_form_title': {}
    'cart.checkout': {}
    'cart.title': {}
    'cart.update': {}
    'cart.remove': {}
    'cart.empty': {}
    'cart.close': {}
    'cart.subtotal': {}
    'cart.error': {}
    'cart.decrease': {}
    'cart.increase': {}
    'cart.item_count': { count: number }
    'customers.login.email': {}
    'customers.login.password': {}
    'customers.login.submit': {}
    'customers.login.title': {}
    'collections.title': {}
    'gift_card.add_to_apple_wallet': {}
    'gift_card.card': {}
    'gift_card.expired': {}
    'gift_card.expires_on': { expires_on: string | number }
    'gift_card.use_at_checkout': {}
    'password.title': {}
    'password.password': {}
    'password.enter': {}
    'product.add_to_cart': {}
    'product.sold_out': {}
    'product.unavailable': {}
    'product.quantity': {}
    'search.title': {}
    'search.placeholder': {}
    'search.submit': {}
    'search.no_results_html': { terms: string | number }
    'search.results_for_html': { count: string | number; terms: string | number }
  }
}
