// Types for the virtual module generated by @shopify-modern/vite-plugin.
// Add "@shopify-modern/vite-plugin/client" to "types" in the theme's tsconfig.json.
declare module 'virtual:islands' {
  import type { IslandRegistry } from '@shopify-modern/islands'

  /** The island registry, generated from the island folder (`src/islands/` by default). */
  export const islands: IslandRegistry
}
