// Types for the virtual module generated by @pelagojs/vite-plugin.
// Add "@pelagojs/vite-plugin/client" to "types" in the theme's tsconfig.json.
declare module 'virtual:islands' {
  import type { IslandRegistry } from '@pelagojs/islands'

  /** The island registry, generated from the island folder (`src/islands/` by default). */
  export const islands: IslandRegistry
}
